# DVC Pipeline Configuration
# Vietnamese-English Code-Switching Speech Translation Pipeline
#
# Data tracked separately via `dvc add`:
#   - data/raw.dvc: Raw audio and text files
#   - data/db_sync.dvc: PostgreSQL database exports for sync
#
# Stages for processing pipelines (run with `dvc repro`):
#   - export_reviewed: Export human-reviewed samples to structured output

stages:
  # Export reviewed samples to data/reviewed/ directory
  export_reviewed:
    cmd: python src/export_reviewed.py
    deps:
      - src/export_reviewed.py
      - src/utils/data_utils.py
    outs:
      - data/reviewed:
          cache: true
          persist: true
    # Run after each review session or on schedule
    # Manual trigger: dvc repro export_reviewed

# Plots configuration for tracking metrics (optional)
# plots:
#   - data/reviewed/manifest.json:
#       x: task_types
#       y: total_samples

# Parameters (can be overridden via params.yaml)
# params:
#   - params.yaml:
#       - export.task_type
#       - export.limit
