# DVC Pipeline Configuration
# Vietnamese-English Code-Switching Speech Translation Pipeline
#
# Data tracked via `dvc add`:
#   - data/raw.dvc: Raw audio files from YouTube
#
# Stages for processing pipelines (run with `dvc repro`):
#   - export_final: Export approved segments to HuggingFace dataset format
#
# Updated: December 2025 (SQLite + Streamlit workflow)

stages:
  # Export approved segments to data/export/ directory
  export_final:
    cmd: python src/export_final.py
    deps:
      - src/export_final.py
      - src/db.py
      - data/lab_data.db
    outs:
      - data/export:
          cache: true
          persist: true
    # Run after review session to generate training data
    # Manual trigger: dvc repro export_final

# Plots configuration for tracking metrics (optional)
# plots:
#   - data/export/manifest.tsv:
#       x: duration_ms
#       y: count
